function getPhrase(){
    document.getElementById('one').innerText = verbs[Math.floor(Math.random() * verbs.length)];
    document.getElementById('two').innerText = adjectives[Math.floor(Math.random() * adjectives.length)] + " " + adjectives[Math.floor(Math.random() * adjectives.length)];
    document.getElementById('three').innerText = nouns[Math.floor(Math.random() * nouns.length)];

}

let verbs = [
    'recognized',
    'performed',
    'achieved',
    'maintained',
    'expected',
    'strived',
    'excelled',
    'avoided',
    'conformed',
    'met',
    'kept',
    'provided',
    'forecasted',
    'made',
    'attained',
    'focused',
    'produced',
    'exceeded',
    'accomplished',
    'demonstrated',
    'examined',
    'encouraged',
    'avoided',
    'used',
    'established',
    'enumerated',
    'developed',
    'improved',
    'expedited',
    'supplied',
    'managed',
    'controlled',
    'developed',
    'engineered',
    'designed',
    'decreased',
    'maximized',
    'minimized',
    'utilized',
    'analyzed',
    'created'
]
let adjectives = [
    'strong',
    'efficient',
    'quick',
    'manual',
    'helper',
    'cross-functional',
    'gender-focused',
    'gender-inclusive',
    'existing',
    'previous',
    'future',
    'current',
    'monthly',
    'weekly',
    'daily',
    'biannual',
    'unprecedented',
    'post-COVID',
    'pre-COVID',
    'best',
    'aesethtically pleasing',
    'readable',
    'DRY',
    'test score',
    'independent',
    'analytical',
    'data-based',
    'data-focused',
    'inaugural',
    'office',
    'proprietary',
    'uneccesary',
    'negative',
    'positive',
    'linear',
    'extreme',
    'slight',
    'moderate',
    'fewer',
    'accurate',
    'strict',
    'precise',
    'explicit',
    'technical',
    'business',
    'administrative',
    'better',
    'high',
    'low',
    'appropriate',
    'personal',
    'organizational',
    'good',
    'mean',
    'average',
    'excellent',
    'proper',
    'competent',
    'forcefully',
    'accurately',
    'intellectual', 
    'mobile',
    'web',
    'iOS',
    'android', 
    'linux',
    'macOS',
    'windows'
  
]

let nouns = [
    'app',
    'website',
    'websocket',
    'processes',
    'system',
    'backend', 
    'frontend', 
    'UI',
    'teams',
    'html',
    'css',
    'javascript',
    'python',
    'react',
    'goals',
    'workplace',
    'jira',
    'figma',
    'photoshop'

]